# Generated by Django 4.0.6 on 2022-07-26 00:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_two',
            field=markdownx.models.MarkdownxField(default='New post coming soon.'),
            preserve_default=False,
        ),
    ]
