# Generated by Django 4.0.6 on 2022-07-21 12:38

from django.db import migrations, models
from django.template.defaultfilters import slugify

def add_slugs(apps, schema_editor):
    Post = apps.get_model('website', 'Post')
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_page_body_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
        migrations.RunPython(add_slugs),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True)
        ),
    ]
