# Generated by Django 4.0.6 on 2022-07-26 01:58

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_body_three'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_three',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
