# Generated by Django 4.0.6 on 2022-07-22 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 2, 6, 23, 92877)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 2, 6, 35, 669909)),
            preserve_default=False,
        ),
    ]
