# Generated by Django 4.0.6 on 2022-07-25 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_header_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
